const papersInfo = [
  {
    id: 0, isMoved: false, isSelected: false, layout: 'option2', 
    width: 1035,
    translateY: '20px', scrollMarginTop: '80px',
    gridColumns: 'min(70px, 17%) min(50px, 11%) min(65px, 15%) min(90px, 21%)',
    gridRows: '100%',
    title: 'The Impact of Filtering Social Media Push Notifications on Well-being and Social Media Usage',
    typeTitle: `Master's Thesis`,
    secondaryTitle: `Experimental Field Study`,
    alt: `Master's Thesis, Experimental Field Study`,
    abstractExtra: `\nThis thesis investigated whether filtering SM push notifications based on their importance affects well-being, social media usage, and user experience. Specifically, notifications related to direct messages and offline events were assumed important, based on previous findings regarding the importance of smartphone notifications.\n\nAn experimental field study was conducted with 16 young adults using Facebook, Instagram, and TikTok. Participants were divided into a control group with default notification settings and a treatment group with filtered notifications. Well-being was measured through surveys administered before, during, and after the two-week experiment, while social media activity was tracked using platform-provided data donations. Interviews were conducted to understand participants' experiences.\n\nThe results showed that SM notifications about one-on-one messages were valued most, followed by traditional SM notifications, while most notification types were perceived as unimportant. Filtering notifications did not significantly affect well-being between the groups, but mindfulness increased within the treatment group. Social media usage remained largely unchanged, although the number of searches increased within the treatment group. Additionally, daily reactions were associated with higher stress and lower positive affect on that day.\n\nBeyond these findings, the analysis of data donations revealed differences in data quality and structure across platforms, and highlighted the challenges and time required due to missing documentation. Facebook data donations were particularly problematic. Overall, the findings suggest that filtering SM notifications based on perceived importance is a feasible and non-harmful alternative to more restrictive notification management strategies, and that the use of data donations should be carefully considered during study design.`,
    abstract: `Social media (SM) use has been shown to affect well-being both positively and negatively, with push notifications contributing negatively by causing distraction and mental fatigue. In addition, social media notifications encourage platform use, potentially reinforcing the negative effects of these platforms. However, prior research has also shown that muting notifications altogether can negatively affect well-being, suggesting a need for more nuanced approaches to managing SM push notifications.`,
    preview: '',
    link: 'https://aaltodoc.aalto.fi/items/e55e0e0d-c950-494d-9df2-8f7c93b7d780',
    date: '03/2025 - 12/2025',
    images: []
  },
  {
    id: 1, isMoved: false, isSelected: false, layout: 'option2',
    width: 1035,
    translateY: '60px', scrollMarginTop: '195px',
    gridColumns: 'min(63px, 14%) min(110px, 28%) min(90px, 21%)',
    gridRows: '50% 50%',
    title: 'Design Guidelines For Interactive Information Visualizations',
    typeTitle: `Bachelor's Thesis`,
    secondaryTitle: `Systematic Literature Review`,
    alt: `Bachelor's Thesis, Systematic Literature Review`,
    abstractExtra: `\nThe derived guidelines can be divided into general guidelines, concrete guidelines about interaction and into guidelines about visual aspects. Firstly, the visual representations should not be too detailed. They should be simple enough but there could be a possibility to explore the data further according to the user's needs. Regarding interaction and its elements, it is important that the interface provides immediate feedback and a possibility for direct manipulation of the visual representations. The interface should also support smooth transitions and not require memorization from the user.\n\nRegarding visual guidelines, layout design is explored, and one observation is that information visualizations should be fitted on the screen and displayed at once. This makes the comparison between different views and aspects of the data easier. In addition, the use of color with interactive visualizations is explored.\n\nThe design process of an interface for interactive information visualizations is not straightforward and the guidelines presented in this thesis should be followed with the designer's use case in mind. However, the results in this thesis give a baseline for the design of these interfaces that can then be complemented with the knowledge from other fields.`,
    abstract: `Design guidelines have been constructed for some interface types, but guidelines are missing for interfaces that visualize statistical data and offer a possibility to alter the data and its representations. Constructing design guidelines for these interfaces would however help the work of a designer. Thus, this thesis focuses on constructing design guidelines for interactive information visualizations. The guidelines are constructed by considering the general public as the user. The guidelines are constructed by conducting a literature review.`,
    preview: '',
    link: 'https://aaltodoc.aalto.fi/items/cd2758fa-2ced-4595-aa19-c71acad1144d',
    date: '09/2023 - 12/2023',
    //datePosition: 'absolute',
    images: []
  },
  {
    id: 2, isMoved: false, isSelected: false, layout: 'option2',
    width: 1035, imageWidth: 997, imageHeight: 'auto',
    translateY: '60px', scrollMarginTop: '195px',
    gridColumns: 'min(63px, 14%) min(110px, 28%) min(90px, 21%)',
    gridRows: '50% 50%',
    title: 'The Impact of Visual Warnings on User Trust in LLM-Generated References',
    secondaryTitle: `Between-Subjects Experimental Study`,
    image: "the_impact_of_visual_warnings.png",
    alt: `Between-Subjects Experimental Study`,
    abstractExtra: `\nThis study investigated how two types of visual warnings, a text warning and a modal warning, affected users’ trust in AI during a reference list creation task. Participants completed the task with the help of an LLM tool, after which their trust in AI was measured using a ques- tionnaire. During the task, participants were exposed to one of the two warnings or no warning at all.\n\nResults showed that the presence of warnings increased trust in AI, contrary to our hypothesis that a more prominent warning would reduce trust. Furthermore, the presence of warnings was associated with less verification behavior regarding the legitimacy of the generated references. Participants also provided positive feedback about the modal warning, while the text warning was perceived as unnoticeable, although some participants disregarded both.\n\nThis study offers insights into how visual warnings can paradoxically increase trust in AI and how even more alerting options would be needed. Additionally, it provides a foundation for designing AI warnings and interfaces that balance trust and transparency. Further research with a larger sample size is needed to better understand the impact of warnings on trust in AI.`,
    abstract: `Generative large language models (LLMs) such as ChatGPT are known to confidently produce false or misleading textual informa- tion, a phenomenon often referred to as “hallucinations”. Although there are advances in detecting and mitigating these hallucinations, and subtle disclaimers such as “ChatGPT can make mistakes” ex- ist, there is limited research on how to effectively communicate these risks to users through visual warnings. There is also limited understanding of how such warnings impact trust in human-AI collaboration. This gap is particularly relevant in common tasks requiring factual accuracy, such as generating reference lists.`,
    preview: '',
    link: '/files/the_impact_of_visual_warnings.pdf',
    date: '01/2025 - 05/2025',
    //datePosition: 'absolute',
    images: []
  },
  {
    id: 3, isMoved: false, isSelected: false, layout: 'option2',
    width: 1035,
    translateY: '60px', scrollMarginTop: '195px',
    gridColumns: 'min(63px, 14%) min(110px, 28%) min(90px, 21%)',
    gridRows: '50% 50%',
    title: 'Comparative Analysis of CSS Frameworks',
    secondaryTitle: `Experimental Comparative Study`,
    alt: `Experimental Comparative Study`,
    abstractExtra: ``,
    abstract: `This paper presents a comparative analysis of three widely used CSS frameworks - Bootstrap, Tailwind CSS and Foundation. The comparison aims to discover the optimal use cases for each framework by focusing on their documentation, ease of use, responsiveness and customisation capabilities. To conduct the analysis, three identical websites were built with each framework and the development process was thoroughly documented. This paper showcases the findings of the developers, identifying the strengths and weaknesses of the frameworks and offering guidance on the kind of projects they would be most compatible with.`,
    preview: '',
    link: '/files/comparative_analysis_of_CSS.pdf',
    date: '10/2024 - 12/2024',
    //datePosition: 'absolute',
    images: []
  },
  {
    id: 4, isMoved: false, isSelected: false, layout: 'option2',
    width: 1035,
    translateY: '60px', scrollMarginTop: '195px',
    gridColumns: 'min(63px, 14%) min(110px, 28%) min(90px, 21%)',
    gridRows: '50% 50%',
    title: 'Various Aspects to Consider in Choosing User-Centered Methods',
    secondaryTitle: `Essay`,
    alt: `Essay`,
    abstractExtra: ``,
    abstract: `This essay looks at the benefits and deficits of different user-centered methods, and their applicability. This is done by first introducing user-centered activities and discussing the importance of using multiple methods in a flexible manner. After that, different methods are introduced and discussed by walking through some of the user-centered activities, each having a section of their own. Finally, the contents of this essay are summarized.`,
    preview: '',
    link: '/files/various_aspects_to_consider.pdf',
    date: '09/2023 - 10/2023',
    //datePosition: 'absolute',
    images: []
  },
];

export default papersInfo;