const projectsInfo = [
  {
    id: 0, isMoved: false, isSelected: false, layout: 'option2', 
    width: 500, imageWidth: 335, imageHeight: 335,
    translateY: '20px', scrollMarginTop: '80px',
    gridColumns: 'min(70px, 17%) min(50px, 11%) min(65px, 15%) min(90px, 21%)',
    gridRows: '100%',
    title: 'Memory Game',
    image: "memory_game.png",
    alt: 'Memory Game',
    technologies: ['Flutter', 'Dart', 'Flame', 'Firebase'],
    description: `This application is a memory game with three levels that increase in difficulty. The project was developed to practice using the Flame game engine with Flutter and Dart. It also demonstrates my ability to customize Flutter's default design. The application is hosted by Firebase Hosting.`,
    github: 'https://github.com/viivi-uhari/memory-game',
    link: 'https://memory-game-4e0b3.web.app',
    date: '11/2024',
    images: []
  },
  {
    id: 1, isMoved: false, isSelected: false, layout: 'option2',
    width: 500,
    translateY: '60px', scrollMarginTop: '195px',
    gridColumns: 'min(63px, 14%) min(110px, 28%) min(90px, 21%)',
    gridRows: '50% 50%',
    title: 'CSS Framework Comparison',
    image: "css_comparison.png",
    alt: 'CSS Framework Comparison',
    technologies: ['HTML', 'CSS', 'Bootstrap', 'Foundation', 'Tailwind', 'Firebase'],
    description: `This project compares three different CSS frameworks, Bootstrap, Foundation, and Tailwind, and was conducted as part of research into developments in the field of web software development. I worked on this project with two other students, and the findings are documented under my academic papers. The application has been deployed using Firebase.`,
    github: 'https://github.com/kiiamakir/css-framework-comparison',
    link: 'https://css-framework-comparison.web.app',
    date: '11/2024',
    //datePosition: 'absolute',
    images: []
  },
  {
    id: 2, isMoved: false, isSelected: false, layout: 'option2',
    width: 500,
    translateY: '60px', scrollMarginTop: '195px',
    gridColumns: 'min(70px, 17%) min(50px, 11%) min(90px, 21%)',
    gridRows: '100%',
    title: 'Restaurant Diary',
    image: "restaurant_diary.png",
    alt: 'Restaurant Diary',
    technologies: ['Flutter', 'Dart', 'Firebase'],
    description: `This Flutter application is a simple website for storing information about visited restaurants. The application allows users to rate restaurants, record their prices, and write notes about them. The application has been deployed using Firebase.`,
    github: 'https://github.com/viivi-uhari/restaurant-diary',
    link: 'https://dad-project1-b8808.web.app/',
    date: '10/2024',
    //datePosition: 'absolute',
    images: []
  },
  {
    id: 3, isMoved: false, isSelected: false, layout: 'option2',
    width: 500,
    translateY: '60px', scrollMarginTop: '195px',
    gridColumns: 'min(105px, 25%) min(65px, 15%) min(75px, 17%) min(110px, 100%)',
    gridRows: '50% 50%',
    title: 'Q&A about Courses',
    image: "questions_and_answers.png",
    alt: 'Q&A about Courses',
    technologies: ['JavaScript', 'Tailwind', 'Astro', 'Svelte', 'NGINX', 'Docker', 'Kubernetes'],
    shortTechnologies: ['JavaScript', 'Tailwind', 'Astro', 'Svelte', 'NGINX', 'Docker', 'K8s'],
    description: `This project was a practice exercise in building a scalable web application. The application lists courses where users can ask and answer questions. An LLM also generates three answers for each question. The application utilizes load balancing, server-sent events, message queues, infinite scrolling, and cached requests. In addition, a Kubernetes configuration was implemented for container orchestration.`,
    github: 'https://github.com/viivi-uhari/qa-app',
    date: '07/2024',
    //datePosition: 'absolute',
    images: []
  },
  {
    id: 4, isMoved: false, isSelected: false, layout: 'option2',
    width: 500,
    translateY: '60px', scrollMarginTop: '195px',
    gridColumns: 'min(105px, 25%) min(65px, 15%) min(70px, 17%)',
    gridRows: '50% 50%',
    title: 'Grading Code Assignments',
    image: "grading_code.png",
    alt: 'Grading Code Assignments',
    technologies: ['JavaScript', 'Tailwind', 'Astro', 'Svelte', 'NGINX', 'Docker'],
    description: `This project also demonstrates my knowledge of scalable web application features. The application consists of three Python programming assignments that are graded using a Docker-based grader image (not implemented by me). The application provides real-time updates on the grading process without requiring the user to refresh the page. In addition, load balancing and queues for assignment submissions have been implemented.`,
    github: 'https://github.com/viivi-uhari/programming-assignments-app',
    date: '06/2024',
    //datePosition: 'absolute',
    images: []
  },
  {
    id: 5, isMoved: false, isSelected: false, layout: 'option2', 
    width: 500, 
    translateY: '20px', scrollMarginTop: '80px',
    gridColumns: 'min(105px, 25%) min(72px, 18%) min(70px, 15%)',
    gridRows: '50% 50%',
    title: 'Recipe Stash',
    image: "recipe_stash.png",
    alt: 'Recipe Stash',
    technologies: ['JavaScript', 'Mongo DB', 'React', 'Node.js', 'CSS', 'Figma'],
    description: `This web application is meant for storing recipes quickly and easily so that they can be found in the same location. The idea was to simplify existing recipe applications into a cleaner and more attractive version for users who live busy lives. The application was developed in a three-person team, and we designed it carefully with the help of personas, use cases, and user stories.`,
    github: 'https://github.com/portmil/recipe-stash',
    link: 'https://recipe-stash.onrender.com',
    date: '09/2023 - 11/2023',
    //datePosition: 'absolute',
    images: [
      {src: 'recipe_stash_buttons.png', width: 161, height: 513, top: 72, left: 50}, 
      {src: 'recipe_stash_drafts.png', width: 293, height: 239, top: 190, left: 240},
      {src: 'recipe_stash_fonts.png', width: 301, height: 208, top: 450, left: 240},
      {src: 'recipe_stash_colors.png', width: 234, height: 368, top: 283, left: 570},
      {src: 'recipe_stash_home.png', width: 153, height: 304, top: 40, left: 830},
      {src: 'recipe_stash_cooking.png', width: 153, height: 304, top: 40, left: 1000},
      {src: 'recipe_stash_ranking.png', width: 444, height: 261, top: 360, left: 840},
      {src: 'recipe_stash_search.png', width: 209, height: 270, top: 70, left: 1175}
    ]
  },
  {
    id: 6, isMoved: false, isSelected: false, layout: 'option2', 
    width: 500, imageWidth: 300, imageHeight: 300,
    translateY: '50px', scrollMarginTop: '80px',
    gridColumns: 'min(105px, 25%) min(65px, 15%) min(150px, 100%)',
    gridRows: '50% 50%',
    title: 'Inclusive Helsinki',
    image: "inclusive_helsinki.png",
    alt: 'Inclusive Helsinki',
    technologies: ['JavaScript', 'React', 'CSS', 'Figma', 'DaVinci Resolve'],
    shortTechnologies: ['JavaScript', 'React', 'CSS', 'Figma', 'DaVinci R.'],
    description: `This application was a practice project in creating a campaign page using frontend technologies. The project was completed in pairs, and we chose to focus on the issue of hostile architecture. The page is based on mock data but still features relevant content. It also incorporates a video related to the campaign.`,
    github: 'https://github.com/viivi-uhari/vjp-final-project',
    link: 'https://inclusive-helsinki.web.app',
    date: '04/2023',
    //datePosition: 'absolute',
    images: [
      {src: 'inclusive_helsinki_colors.png', width: 406, height: 215, top: 80, left: 60}, 
      {src: 'inclusive_helsinki_drafts.png', width: 600, height: 262, top: 330, left: 60},
      {src: 'inclusive_helsinki_video.png', width: 528, height: 221, top: 80, left: 500},
      {src: 'inclusive_helsinki_home.png', width: 340, height: 297, top: 320, left: 680},
      {src: 'inclusive_helsinki_form.png', width: 301, height: 416, top: 40, left: 1075},
      {src: 'inclusive_helsinki_signature.png', width: 350, height: 114, top: 460, left: 1035},
    ]
  },
  {
    id: 7, isMoved: false, isSelected: false, layout: 'option2',
    width: 500, imageWidth: 322, imageHeight: 300, 
    translateY: '60px', scrollMarginTop: '195px',
    gridColumns: 'min(100px, 24%) min(75px, 15%) min(75px, 14%) min(180px, 100%)',
    gridRows: '50% 50%',
    title: 'Aalto Grades',
    image: "aalto_grades.png",
    alt: 'Aalto Grades',
    technologies: ['JavaScript', 'TypeScript', 'React', 'Node.js', 'Docker', 'MUI', 'Styled Components', 'Figma'],
    shortTechnologies: ['JavaScript', 'TypeScript', 'React', 'Node.js', 'Docker', 'MUI', 'Styled C.', 'Figma'],
    description: `This application was developed in collaboration with Aalto University, and it was designed to help teachers calculate students’ grades more easily. The application would also allow students to check their progress in different courses. The application was developed in a Scrum team of nine people (eight developers and one Scrum Master).`,
    github: 'https://github.com/aalto-grades/base-repository',
    date: '10/2022 - 04/2023',
    images: [
      {src: 'aalto_grades_home.png', width: 646, height: 396, top: 45, left: 45}, 
      {src: 'aalto_grades_github.png', width: 459, height: 168, top: 455, left: 45},
      {src: 'aalto_grades_warning.png', width: 172, height: 152, top: 455, left: 510},
      {src: 'aalto_grades_results.png', width: 531, height: 215, top: 45, left: 702},
      {src: 'aalto_grades_edit.png', width: 389, height: 314, top: 315, left: 702},
      {src: 'aalto_grades_csv.png', width: 293, height: 204, top: 315, left: 1102}
    ]
  },
  {
    id: 8, isMoved: false, isSelected: false, layout: 'option2',
    width: 500,
    translateY: '40px', scrollMarginTop: '83px',
    gridColumns: 'min(100px, 26%) min(50px, 11%) min(130px, 28%)',
    gridRows: '50% 50%',
    title: 'Popularity of Vaccines',
    image: "vaccines.png",
    alt: 'Popularity of Vaccines',
    technologies: ['JavaScript', 'HTML', 'CSS', 'D3', 'Observable'],
    description: `This interactive and dynamic visualization provides information about the popularity of different vaccinations. The visualization was implemented in Observable and displays data on vaccination coverage for different diseases as well as attitudes toward vaccines. With this project, my goal was to practice creating dynamic visualizations with D3.`,
    link: 'https://observablehq.com/d/a97ddbd4dde8ab5b',
    date: '11/2023 - 12/2023',
    images: [
      {src: 'vaccines_desktop.png', width: 806, height: 508, top: 60, left: 60},
      {src: 'vaccines_map.png', width: 402, height: 268, top: 30, left: 910},
      {src: 'vaccines_line_chart.png', width: 418, height: 309, top: 320, left: 960}
    ]
  },
  {
    id: 9, isMoved: false, isSelected: false, layout: 'option2',
    width: 500, imageWidth: 395, imageHeight: 365,
    translateY: '50px', scrollMarginTop: '80px',
    gridColumns: '100%',
    gridRows: '100%',
    title: 'Planting Trees',
    image: "trees.png",
    alt: 'Planting Trees',
    technologies: ['Figma'],
    description: `This UI prototype is part of a project in which our goal was to design a graphical user interface for planting trees in a team of four. The GUI was divided into different views, and I focused on displaying the progress of planting trees. The view shows the user's progress as well as their community's progress, as the users are motivated to improve their local community's environment.`,
    link: 'https://www.figma.com/proto/2BAzFEv0n18AfOTy20wvr4/tree-app?page-id=0%3A1&type=design&node-id=1-252&viewport=499%2C323%2C0.3&t=YBq1lDSvDDTW4UZr-1&scaling=scale-down&starting-point-node-id=1%3A252&mode=design',
    date: '11/2023 - 12/2023',
    images: [
      {src: 'trees_popup.png', width: 180, height: 355, top: 50, left: 45},
      {src: 'trees_scrolled.png', width: 180, height: 355, top: 50, left: 235},
      {src: 'trees_filtered.png', width: 180, height: 355, top: 50, left: 425},
      {src: 'trees_colors.png', width: 519, height: 172, top: 430, left: 45},
      {src: 'trees_icons.png', width: 375, height: 71, top: 90, left: 650},
      {src: 'trees_drafts.png', width: 342, height: 384, top: 200, left: 670},
      {src: 'trees_components.png', width: 280, height: 181, top: 75, left: 1045},
      {src: 'trees_nav.png', width: 270, height: 384, top: 220, left: 1130}
    ]
  },
  {
    id: 10, isMoved: false, isSelected: false, layout: 'option2',
    width: 500, imageWidth: 390, imageHeight: 303,
    translateY: '50px', scrollMarginTop: '80px',
    gridColumns: '100%',
    gridRows: '100%',
    title: 'Tietokilta - Website',
    image: "tietokilta.png",
    alt: 'Tietokilta - Website',
    technologies: ['Figma'],
    description: `I have been part of the team responsible for designing my guild Tietokilta's new website. I focused on the content pages and on how textual and graphical information would be displayed.`,
    link: 'https://tietokilta.fi',
    date: '02/2023',
    images: []
  },
  {
    id: 11, isMoved: false, isSelected: false, layout: 'option2',
    width: 500,
    translateY: '50px', scrollMarginTop: '110px',
    gridColumns: 'min(60px, 14%) min(115px, 30%) min(70px, 11%)',
    gridRows: '100%',
    title: 'Virtual Cassino',
    image: "virtual_cassino.png",
    alt: 'Virtual Cassino',
    technologies: ['Scala', 'Scala Swing', 'UML'],
    description: `This virtual Cassino card game was created during the second year of my bachelor's degree. The game can be run locally and can be played either against other players (on the same computer) or against computer opponents. The project demonstrates my knowledge of Scala and object-oriented programming.`,
    github: 'https://github.com/viivi-uhari/virtual-cassino',
    date: '02/2021 - 04/2021',
    images: [
      {src: 'cassino_player1.png', width: 399, height: 313, top: 100, left: 75}, 
      {src: 'cassino_computer2.png', width: 399, height: 313, top: 195, left: 505},
      {src: 'cassino_clubs.png', width: 57, height: 65, top: 100, left: 672},
      {src: 'cassino_spades.png', width: 45, height: 49, top: 100, left: 740},
      {src: 'cassino_heart.png', width: 50, height: 49, top: 100, left: 790},
      {src: 'cassino_diamond.png', width: 40, height: 49, top: 100, left: 862},
      {src: 'cassino_uml.png', width: 423, height: 600, top: 40, left: 935}
    ]
  },
  /*
  {
    id: 12, isMoved: false, isSelected: false, layout: 'option2',
    width: 500, imageWidth: 390, imageHeight: 303,
    translateY: '50px', scrollMarginTop: '80px',
    gridColumns: 'min(60px, 14%) min(100px, 25%) min(120px, 30%)',
    gridRows: '100%',
    title: 'Christmas Cards',
    image: "christmas_cards.png",
    alt: 'Christmas Cards',
    technologies: ['Scala', 'Java AWT', 'Scala Swing'],
    description: `As one of the first projects at Aalto University, we created Christmas cards using Scala and Java AWT. The cards included graphics, text, and animation. My card featured swinging, color-changing Christmas lights.`,
    github: 'https://github.com/viivi-uhari/christmas-cards',
    date: '11/2020',
    images: []
  },
  {
    id: 13, isMoved: false, isSelected: false, layout: 'option2',
    width: 500, imageWidth: 390, imageHeight: 303,
    translateY: '50px', scrollMarginTop: '80px',
    gridColumns: 'min(60px, 14%) min(120px, 30%)',
    gridRows: '100%',
    title: 'Shopping at IKEA',
    image: "shopping_at_ikea.png",
    alt: 'Shopping at IKEA',
    technologies: ['Scala', 'Scala Swing'],
    description: `A simple dialog-based adventure game where the player tries to find and collect the correct IKEA items. This project was created as practice for developing a Scala Swing game.`,
    github: 'https://github.com/viivi-uhari/shopping-at-ikea',
    date: '10/2020',
    images: []
  },
  {
    id: 12, isMoved: false, isSelected: false, layout: 'option2',
    width: 500,
    translateY: '50px', scrollMarginTop: '80px',
    gridColumns: 'min(110px, 27%) min(100px, 26%) min(60px, 17%)',
    gridRows: '50% 50%',
    title: 'Simple Web Application',
    image: '',
    alt: 'Simple Web Application',
    technologies: ['JavaScript', 'HTML', 'CSS', 'Bootstrap', 'SQL', 'Deno'],
    description: 'This simple web application is meant for creating and answering questions and it has been created as a part of the Web Software Development course. The application hasn’t been deployed but it can be run locally by following the instructions given in Github. This project demonstrates basic full stack development skills.',
    github: 'https://github.com/viivi-uhari/question-web-app',
    date: '11/2021 - 12/2021',
    images: []
  },
  {
    id: 13, isMoved: false, isSelected: false, layout: 'option2',
    width: 500,
    translateY: '50px', scrollMarginTop: '80px',
    gridColumns: 'min(40px, 6%) min(110px, 33%)',
    gridRows: '100%',
    title: 'Student Database',
    image: '',
    alt: 'Student Database',
    technologies: ['C', 'Valgrind'],
    description: `This simple project demonstrates my basic knowledge of c, and it is for creating and handling a student "database". The application can be run locally, and the data is only stored in memory while the application is running.`,
    github: 'https://github.com/viivi-uhari/student-database',
    date: '08/2021',
    images: []
  },
  */
];

export default projectsInfo;