import '@/app/ui/global.css';
import Navigation from './components/navigation';

export const metadata = {
  title: 'Portfolio of Viivi Uhari',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body>
        <Navigation/>
        {children}
      </body>
    </html>
  )
}
